packages:
- '.'
- location:
    git: https://github.com/vaibhavsagar/duffer.git
    commit: bcd32cae282eaafee6a91d21a58172cf6597424a
  subdirs:
    - duffer
    - duffer-json
  extra-dep: true
resolver: lts-8.11
