packages:
- '.'
- location:
    git: https://github.com/vaibhavsagar/duffer.git
    commit: cebcb3302302809f25c190c5add9bb720dcb0493
  subdirs:
    - duffer
    - duffer-json
  extra-dep: true
resolver: lts-9.0
