flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:vaibhavsagar/duffer
    commit: 8996002ee6a94cd9ac31b0c6bdcb8e59be835984
  extra-dep: true
extra-deps:
- http-api-data-0.3.2
- pipes-zlib-0.4.4.1
- servant-0.9.1.1
- servant-server-0.9.1.1
resolver: lts-6.30
