flags: {}
extra-package-dbs: []
packages:
- '.'
- duffer
extra-deps:
- aeson-1.0.2.1
- bytestring-builder-0.10.8.1.0
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- http-api-data-0.3.2
- pipes-zlib-0.4.4.1
- servant-0.9.1.1
- servant-server-0.9.1.1
resolver: lts-6.24
