packages:
- '.'
- location:
    git: https://github.com/vaibhavsagar/duffer.git
    commit: 404bad52e35b4641c99abfadd117546879804036
  subdirs:
    - duffer
    - duffer-json
  extra-dep: true
resolver: lts-8.15
